In [8]:
import numpy as np
a = [[1,2,3], [4,5,6], [7,8,9]]
a = np.array(a)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
b = np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
(a + b).astype(int)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
a[a%2 == 0] = 0
a

array([[1, 0, 3],
       [0, 5, 0],
       [7, 0, 9]])

In [32]:
isinstance(np.array([1]), np.ndarray)

True

In [15]:
class My_class:
    def __init__(self, arr):
        self.arr = arr
    def __add__(self, other):
        return self.arr + 2 * other

arr = My_class(np.array([1,2,3]))


In [16]:
arr + 1

array([3, 4, 5])