In [2]:
import numpy as np
a = [[1,2,3], [4,5,6], [7,8,9]]
a = np.array(a)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
b = np.ones((3,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [4]:
(a * b).astype(int)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
a[a%2 == 0] = 0
a

array([[1, 0, 3],
       [0, 5, 0],
       [7, 0, 9]])

In [6]:
isinstance(np.array([1]), np.ndarray)

True

In [7]:
class My_class:
    def __init__(self, arr):
        self.arr = arr
    def __add__(self, other):
        return self.arr + 2 * other

arr = My_class(np.array([1,2,3]))


In [8]:
np.max(np.zeros((3,3)).data)

0.0

In [11]:
type(np.array((1000 * np.ones((2,2))).astype(int)))

numpy.ndarray

In [37]:
a = np.zeros((2,2,3))
a.shape
a[:,:,0] = np.ones((2,2))
a[:,:,1] = np.ones((2,2))
a[:,:,2] = np.ones((2,2))
a

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])